### PR TITLE
Add snowflake-snowpark-python 0.7.0

### PR DESCRIPTION
**Pull request by skupr-anaconda**
Changelog: https://github.com/snowflakedb/snowpark-python/blob/v0.7.0/CHANGELOG.md
License: https://github.com/snowflakedb/snowpark-python/blob/v0.7.0/LICENSE.txt
Requirements: https://github.com/snowflakedb/snowpark-python/blob/v0.7.0/setup.py

Actions:
1. Skip py<38 or py>=39 or win32 or s390x
2. Remove noarch: python, and make it arch-specific
3. Add setuptools and wheel in host
4. Add license_family
5. Add dev and doc urls

### CODE REVIEW

**Comment by skupr-anaconda** [comment]
The dependent package `snowflake-connector-python` is not currently available on `linux-aarch64`, `linux-s390x`, `osx-arm64`, and `win32`

**Review by tobijk — APPROVED** [review]

**Comment by skupr-anaconda** [comment]
For adding support on arm64 and aarch64 I've rebuild https://github.com/AnacondaRecipes/snowflake-connector-python-feedstock/pull/4

**Review by varlackc — COMMENTED** [review]
should we specify the `pip` version?
https://github.com/snowflakedb/snowpark-python/blob/v0.6.1/tox.ini#L25

should we modify the version of `setuptools`?
https://github.com/snowflakedb/snowpark-python/blob/v0.6.0/recipe/meta.yaml#L28

https://github.com/snowflakedb/snowpark-python/blob/v0.6.1/recipe/meta.yaml#L28

We probably need to verify if the package can build for `linux-aarch64` and `osx-arm64`

**Comment by skupr-anaconda** [comment]
Updated to v0.7.0

**Comment by skupr-anaconda** [comment]
> should we specify the `pip` version? https://github.com/snowflakedb/snowpark-python/blob/v0.6.1/tox.ini#L25
> 
> should we modify the version of `setuptools`? https://github.com/snowflakedb/snowpark-python/blob/v0.6.0/recipe/meta.yaml#L28
> 
> https://github.com/snowflakedb/snowpark-python/blob/v0.6.1/recipe/meta.yaml#L28
> 
> We probably need to verify if the package can build for `linux-aarch64` and `osx-arm64`

@varlackc I'm not sure if setuptools is needed in run. It's already in host. I think the upstream setup.py is incorrect in that place.
pip pinning is needed for testing but we don't run test commands

**Comment by skupr-anaconda** [comment]
`snowflake-connector-python 2.6.2` added on `linux-aarch64` and `osx-arm64` platforms

**Comment by skupr-anaconda** [comment]
It's ready for testing. We can merge it

**Pull request merged**
