### PR TITLE
Add snowflake-snowpark-python 0.6.1

### PR DESCRIPTION
**Pull request by skupr-anaconda**
Changelog: https://github.com/snowflakedb/snowpark-python/blob/v0.6.1/CHANGELOG.md
License: https://github.com/snowflakedb/snowpark-python/blob/v0.6.1/LICENSE.txt
Requirments: https://github.com/snowflakedb/snowpark-python/blob/v0.6.1/setup.py

Actions:
1. Skip py<38 or py>=39 or win32 or s390x
2. Remove noarch: python, and make it arch-specific
3. Add setuptools and wheel in host
4. Add license_family
5. Add dev and doc urls

### CODE REVIEW

**Review by mcg1969 — APPROVED** [review]

**Comment by mcg1969** [comment]
It's interesting that they pushed tag 0.6.1. They created 0.6.0.1 for us specifically but it didn't follow their `v0...` convention

**Comment by skupr-anaconda** [comment]
> It's interesting that they pushed tag 0.6.1. They created 0.6.0.1 for us specifically but it didn't follow their `v0...` convention

Yeah, and they are preparing v0.7.0

**Comment by mcg1969** [comment]
We will be getting heads-up about releases in the future so we can coordinate

**Comment by skupr-anaconda** [comment]
I opened the PR against the `main` branch, but added a submodule to the `master` branch. 
I've opened a new PR https://github.com/AnacondaRecipes/snowpark-python-feedstock/pull/6/

**Pull request closed without merging**
